
require 'bgp/common'
require 'bgp/iana'
require 'bgp/io'
require 'bgp/messages/messages'
require 'bgp/path_attributes/attributes'
require 'bgp/path_attributes/attribute'
require 'bgp/nlris/nlris'
require 'bgp/optional_parameters/capabilities'
require 'bgp/neighbor'
require 'bgp/messages/message'
require 'bgp/version'
